### ISSUE TITLE
очень сложно решено. можно в 2 строки.

### ISSUE THREAD

**Issue by denis-trofimov** [qDes/lesson2#1]
https://github.com/qDes/lesson2/blob/00cc1c58bfda676a1b1461037f1942fb8f73dec2/for_dict_challenges.py#L3-L13

Решая с конца, как только получен список имен, считай все решено.
>>> names
['Вася', 'Петя', 'Маша', 'Маша', 'Петя']
>>> max(names)
'Петя'

https://medium.com/better-programming/lambda-map-and-filter-in-python-4935f248593
Iterating Over a Dictionary Using Map and Lambda но поскольку в примерах был py2 , нужно делать  list(map(lambda x : x['name'], dict_a) )

**Comment by qDes** [comment]
упростил логику и код
